import React from 'react'
import './Contact.scss'

export default function Contact() {
    return (
        <div className='Contact'>
            <p>contact111111111 page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
            <p>contact page</p>
        </div>
    )
}
