import React from 'react'
import './Gallery.scss'

export default function Gallery() {
    return (
        <div className='Gallery'>
            <p>gallery111111111 page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
            <p>gallery page</p>
        </div>
    )
}